adding ListAllRolesForScope function to list Azure Roles
kubescape/k8s-interface pull request #11
Opened 2022-12-24 09:08 UTC by ash-kamrip

Related to : Enrich RoleBinding/ClusterRoleBinding objects with cloud vendor infromation #670 

for Azure AKS Cluster

2022-12-24 09:12 UTC, ash-kamrip commented
Hi @dwertent 

I've added support for listing Azure roles binding Azure identities to AKS cluster. We can probably even implement a method for obtaining Rolebindings within the kubernetes RBAC which would even provide us UPN for single users or GroupId's of the Azure AD groups. kindly Review.

Regards, 
Ashu

2022-12-25 07:00 UTC, dwertent requested changes

2022-12-25 07:09 UTC, ash-kamrip commented on cloudsupport/v1/akssupport.go
> +			log.Fatalf("failed to advance page: %v", err)
Yeah cool , I've commited your suggestion

2022-12-25 07:23 UTC, dwertent approved these changes

2022-12-25 07:24 UTC, merged